name: Calculating Factorial

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Input a number to calculate factorial'
        required: true

jobs:
  run-factorial-script:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make script executable
      run: chmod +x factorial.sh

    - name: Run factorial script
      run: |
        output=$(./factorial.sh ${{ github.event.inputs.number }})
        echo "The factorial Output is: $output"

